name=input("what is your name?")
print(f"hello{name} and be ready for some jokes")
print("When does a joke become a dad joke")
input("")
print("when it becomes a-parent")
input("---------")
print("How do you make a witch itch?")
input("")
print("take away the W")
input("-------")
print("can a bunny jump higher than the eiffel tower?")
input("")
print("Of course because the eiffel tower can't jump")