print("hello my name is John Fabio")
name=input("what is your name")
print(f"hi {name}, and get ready to help with this story")
print(" ")
print(" ")
celebrity=input("pick a celebrity")
if celebrity == "Lebron":
    print("Lebron really is the goat")
    print("good choice")
else:
    print("Oh i like them")
print("")
location=input("now pick a location")
print("")
emotion=input("pick an emotion")
print("")
food=input("pick a food plural")
print("")
print("-----------------")
print(f"one day, {celebrity} was at the {location}, they felt really {emotion}, so he decided to eat {food}")
print("------------------")
print("")
print("")
print("I hope you loved your creation")